# Generated by Django 6.0.7 on 2026-07-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CONF_WEB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_one', models.TextField(blank=True)),
                ('hero_des', models.TextField(blank=True)),
                ('text_scroll', models.TextField(blank=True)),
                ('etiqueta_cat', models.TextField(blank=True)),
                ('titulo_sec_catalogo', models.TextField(blank=True)),
                ('footer', models.TextField(blank=True)),
                ('footer_sub', models.TextField(blank=True)),
                ('atelier', models.TextField(blank=True)),
                ('contacto', models.TextField(blank=True)),
                ('copy', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuracion WEB',
                'verbose_name_plural': 'Configuracion WEB',
            },
        ),
    ]
