# Generated by Django 6.0.7 on 2026-07-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf_web',
            name='sub_title',
            field=models.TextField(blank=True),
        ),
    ]
