# Generated by Django 6.0.7 on 2026-07-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_conf_web_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf_web',
            name='quiet',
            field=models.TextField(blank=True),
        ),
    ]
