# Generated by Django 6.0.7 on 2026-07-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_conf_web_quiet'),
    ]

    operations = [
        migrations.CreateModel(
            name='CATEGORIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
