# Generated by Django 6.0.7 on 2026-07-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0004_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG_PRODUCTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
            ],
            options={
                'verbose_name': 'IMG PRODUCTO',
                'verbose_name_plural': 'IMG PRODUCTO',
            },
        ),
        migrations.CreateModel(
            name='PRODUCTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.TextField(blank=True)),
                ('material', models.TextField(blank=True)),
                ('dimensiones', models.TextField(blank=True)),
                ('categorias', models.ManyToManyField(related_name='categorias', to='modelos.categoria')),
                ('imagenes', models.ManyToManyField(related_name='imagenes', to='modelos.img_producto')),
            ],
            options={
                'verbose_name': 'PRODUCTO',
                'verbose_name_plural': 'PRODUCTOS',
            },
        ),
    ]
