# Generated by Django 6.0.7 on 2026-08-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0005_img_producto_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEDIDO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente_nombre', models.TextField(blank=True)),
                ('cliente_email', models.TextField(blank=True)),
                ('cliente_telefono', models.TextField(blank=True)),
                ('cliente_direccion', models.TextField(blank=True)),
                ('items_json', models.TextField(blank=True)),
                ('total', models.TextField(blank=True)),
            ],
        ),
    ]
