# Generated by Django 6.0.7 on 2026-08-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0006_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf_web',
            name='hero_desc_main',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conf_web',
            name='hero_titulo',
            field=models.TextField(blank=True),
        ),
    ]
