# Generated by Django 6.0.7 on 2026-08-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0007_conf_web_hero_desc_main_conf_web_hero_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf_web',
            name='admin_password',
            field=models.CharField(default='G89qpjksr**', max_length=100),
        ),
    ]
