# Generated by Django 6.0.7 on 2026-08-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0008_conf_web_admin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='agotado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_unico',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
