# Generated by Django 6.0.7 on 2026-08-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0009_pedido_estado_producto_agotado_producto_codigo_unico'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf_web',
            name='base_font_size',
            field=models.TextField(blank=True, default='14px'),
        ),
        migrations.AddField(
            model_name='conf_web',
            name='font_family_base',
            field=models.TextField(blank=True, default="'Lato', sans-serif"),
        ),
        migrations.AddField(
            model_name='conf_web',
            name='font_family_titles',
            field=models.TextField(blank=True, default="'Playfair Display', serif"),
        ),
        migrations.AddField(
            model_name='conf_web',
            name='footer_col1_title',
            field=models.TextField(blank=True, default='Atelier'),
        ),
        migrations.AddField(
            model_name='conf_web',
            name='footer_col2_title',
            field=models.TextField(blank=True, default='Navegación'),
        ),
        migrations.AddField(
            model_name='conf_web',
            name='footer_col3_title',
            field=models.TextField(blank=True, default='Contacto'),
        ),
        migrations.AddField(
            model_name='conf_web',
            name='footer_link_catalogo',
            field=models.TextField(blank=True, default='Catálogo'),
        ),
        migrations.AddField(
            model_name='conf_web',
            name='footer_link_concierge',
            field=models.TextField(blank=True, default='Concierge Private'),
        ),
        migrations.AddField(
            model_name='conf_web',
            name='footer_link_inicio',
            field=models.TextField(blank=True, default='Inicio'),
        ),
        migrations.AddField(
            model_name='conf_web',
            name='meta_description',
            field=models.TextField(blank=True, default='MET | ATELIER - Pura Elegancia a la Moda.'),
        ),
        migrations.AddField(
            model_name='conf_web',
            name='meta_title',
            field=models.TextField(blank=True, default='MET | ATELIER - Pura Elegancia a la Moda.'),
        ),
        migrations.AddField(
            model_name='conf_web',
            name='txt_bolsa_vacia',
            field=models.TextField(blank=True, default='Tu bolsa de compras está vacía.'),
        ),
        migrations.AddField(
            model_name='conf_web',
            name='txt_btn_comprar',
            field=models.TextField(blank=True, default='Solicitar Adquisición'),
        ),
        migrations.AddField(
            model_name='conf_web',
            name='txt_modal_badge',
            field=models.TextField(blank=True, default='Pieza Única de Atelier'),
        ),
        migrations.AddField(
            model_name='conf_web',
            name='txt_modal_checkout_intro',
            field=models.TextField(blank=True, default='Ingresa tus datos de Concierge para coordinar la entrega privada de tus piezas seleccionadas.'),
        ),
        migrations.AddField(
            model_name='conf_web',
            name='txt_modal_checkout_titulo',
            field=models.TextField(blank=True, default='Solicitud de Adquisición'),
        ),
        migrations.AddField(
            model_name='conf_web',
            name='txt_modal_detalle_titulo',
            field=models.TextField(blank=True, default='Detalle de la Pieza'),
        ),
        migrations.AddField(
            model_name='conf_web',
            name='txt_subtotal',
            field=models.TextField(blank=True, default='Subtotal Estimado'),
        ),
    ]
